name: check_scripts

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install packets
      run: sudo apt-get install pycodestyle pylint mypy shellcheck
    - name: Lint with pycodestyle
      run: find -name *.py | xargs pycodestyle
    - name: Lint with pylint
      continue-on-error: true
      run: find -name *.py | xargs pylint
    - name: Typecheck with mypy
      run: find -name *.py | xargs mypy
    - name: Check bash scripts with shellcheck
      run: find -name *.sh | xargs shellcheck
