name: hdl_synthesis

on: [push, pull_request, workflow_dispatch]

jobs:

  synthesis:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Pull docker images
        run: |
          docker pull hdlc/ghdl:yosys
          docker pull hdlc/nextpnr:ice40
          docker pull hdlc/icestorm

      - name: Run synthesis, pnr and packing
        env:
          USE_CONTAINERS: 1
        run: |
          cd syn
          make

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            syn/remote.json
            syn/remote.asc
            syn/remote.bin
