name: hdl_synthesis

on: [push, pull_request]

jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: hdlc/impl
    steps:
      - name: Update git # manually, until git >= 2.18 is available in the container
        run: apt update && apt install --yes git
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run synthesis, pnr and packing
        run: |
          cd syn && ./synth.sh
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            syn/build/remote.json
            syn/build/remote.asc
            syn/build/remote.bin
