name: Check scripts

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install packets
      run: sudo apt-get install pycodestyle pylint3 mypy shellcheck
    - name: Lint with pycodestyle
      run: find -name *.py | xargs pycodestyle
    - name: Lint with pylint
      continue-on-error: true
      run: find -name *.py | xargs pylint3
    - name: Typecheck with mypy
      run: find -name *.py | xargs mypy
    - name: Check bash scripts with shellcheck
      run: find -name *.sh | xargs shellcheck
